openapi: "3.0.0"
components:
  schemas:
    Temperature:
      type: object
      required:
        -id
        -temperature
        -date
      properties:
        id:
          type: integer
          format: int64
        temperature:
          type: string
        date:
          type: string
    Humidity:
      type: object
      required:
        -id
        -humidity
        -date
      properties:
        id:
          type: integer
          format: int64
        humidity:
          type: string
        date:
          type: string
paths:
  /temperatures:
    get:
      summary: List all temperature
      operationId: listTemp
      tags:
        - temps
      parameters:
        -day: limit
        in:query
      responses:
        200:
    post:
      summary: Recieve temperature from IoT device.
      operationId: createTemp
